drop table if exists bookmarks;

create table bookmarks (
    id INTEGER primary key generated by default as identity,
    title TEXT NOT NULL,
    web_address TEXT UNIQUE NOT NULL,
    rating INTEGER NOT NULL,
    desription TEXT
);

insert into bookmarks(title, web_address, rating, desription)
    values
        ('Dummy 1', 'https://dummy1.com', 3, '1'),
        ('Dummy 2', 'https://dummy2.com', 3, '2'),
        ('Dummy 3', 'https://dummy3.com', 3, '3'),
        ('Dummy 4', 'https://dummy4.com', 3, '4'),
        ('Dummy 5', 'https://dummy5.com', 3, '5'),
        ('Dummy 6', 'https://dummy6.com', 3, '6'),
        ('Dummy 7', 'https://dummy7.com', 3, '7'),
        ('Dummy 8', 'https://dummy8.com', 3, '8'),
        ('Dummy 9', 'https://dummy9.com', 3, '9'),
        ('Dummy 10', 'https://dummy10.com', 3, '10');